# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 153)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 30, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.text = QtWidgets.QLineEdit(Dialog)
        self.text.setGeometry(QtCore.QRect(20, 110, 91, 23))
        self.text.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(22, 69, 212, 46))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 110, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Остатки"))
        self.text.setText(_translate("Dialog", "F"))
        self.label.setText(_translate("Dialog", "Введите букву колонки с артикулами"))
        self.label.setWordWrap(True)
        self.pushButton.setText(_translate("Dialog", "Остатки"))
        self.pushButton_2.setText(_translate("Dialog", "Основной файл"))
        self.pushButton_3.setText(_translate("Dialog", "Готово"))
